var Frases = new Array()
/*FINALS*/
Frases[1] = ["Los elastómeros son polímeros que poseen una estructura molecular de cadenas lineales y parcialmente entrecruzadas, lo que permite que el polímero tenga una deformación elástica excepcional.",1];
Frases[2] = ["Los polímeros termoplásticos, una vez fabricados, no se pueden volver a fundir.",0];
Frases[3] = ["En una reacción de polimerización por adición no se crean subproductos y las cadenas poliméricas incrementan su longitud mediante la adición de unidades repetitivas.",1];
Frases[4] = ["Un polímero termoplástico que sólo muestra temperatura de transición vítrea (Tg) tiene que ser necesariamente amorfo.",1];
Frases[5] = ["Un polímero termoplástico que sólo muestra temperatura de transición vítrea (Tg) funde necesariamente a dicha temperatura.",1];
Frases[6] = ["Un polímero termoplástico que muestra comportamiento de sólido vítreo a temperatura ambiente tiene que tener necesariamente una temperatura de transición vítrea mayor que la temperatura ambiente.",1];
Frases[7] = ["Un polímero termoplástico que muestra comportamiento de sólido vítreo a temperatura ambiente podría ser amorfo o semicristalino.",1];
Frases[8] = ["En una reacción peritéctica, dos líquidos de diferente composición química reaccionan para dar lugar a un sólido.",0];
Frases[9] = ["Una aleación segregada químicamente funde a una menor temperatura.",1];
Frases[10] = ["Sabemos que el wolframio (W) y el iridio (Ir) son dos metales que tienen valores muy elevados del módulo de Young al igual que un fuerte carácter refractario/cerámico. Esto se debe a la gran curvatura que poseen los pozos del potencial atómico de estos metales en el entorno de la distancia atómica de equilibrio.",1];
Frases[11] = ["La martensita en los aceros se produce mediante un proceso de temple en condiciones de no equilibrio termodinámico. A mayor cantidad de carbono disuelto en la austenita, mayor dureza tendrá la martensita resultante.",0];
Frases[12] = ["En una reacción invariante incongruente, coexisten en equilibrio termodinámico tres fases.",1];
Frases[13] = ["Un monocristal se deforma plásticamente cuando en alguno de sus sistemas de deslizamiento activos se alcanza la tensión cortante crítica (o tensión de cizalladura crítica resuelta máxima, (Tau)_crss).",1];
Frases[14] = ["El mecanismo de endurecimiento por disolución sólida provoca en realidad un aumento de la tensión cortante crítica (o tensión de cizalladura crítica resuelta máxima, (Tau)_crss).",1];
Frases[15] = ["En una dislocación de cuña (o borde) su vector de Burgers indica la dirección y el sentido del deslizamiento.",1];
Frases[16] = ["A la temperatura de recristalización de la aleación, la totalidad de los granos presentes han sido recristalizados y su tamaño es necesariamente igual al de los granos que existían una vez finalizado el proceso de deformación en frío.",0];
Frases[17] = ["La siguiente ecuación permite explicar el mecanismo de endurecimiento por reducción del tamaño de grano: 𝜎_𝑦=𝜎_0+𝑘∙√𝑑. Siendo 𝜎_y la tensión de límite elástico y d el tamaño de grano, con 𝜎_0 y k dos constantes de ajuste.",0];
Frases[18] = ["Al deformar en frío una aleación metálica se observa un incremento de su tensión de límite elástico. Dicho incremento de tensión está relacionado con una disminución de la densidad de dislocaciones del material.",0];
Frases[19] = ["Al endurecer por precipitación una aleación de aluminio-cobre se observa que su límite elástico aumenta con el tiempo de tratamiento térmico hasta alcanzar un valor máximo para cierto tiempo. Superado este tiempo, su límite elástico disminuye.",1];
Frases[20] = ["La temperatura de recristalización de una aleación endurecida por trabajo en frío es mayor cuanto mayor sea el porcentaje de trabajo en frío que acumula.",0];
Frases[21] = ["Un material metálico que acumula trabajo en frío experimentará crecimiento de grano si se mantiene a su temperatura de recristalización durante más de 1 hora.",1];
Frases[22] = ["Un material metálico deformado a temperatura ambiente no tiene por qué mostrar endurecimiento por deformación en frío ya que podría estar deformándose en caliente.",1];
Frases[23] = ["El mecanismo de endurecimiento por deformación plástica en un material metálico provoca un incremento en su tensión de límite elástico debido a un incremento de su densidad de dislocaciones.",1];
Frases[24] = ["En un sistema isomórfico binario siempre es posible encontrar una aleación que posea una tensión de límite elástico mayor que las respectivas tensiones de límite elástico de sus elementos puros.",1];
Frases[25] = ["En un diagrama de fases de solubilidad total, una aleación que presente segregación química fundirá a una temperatura menor que si hubiera sido enfriada en condiciones de equilibrio.",1];
Frases[26] = ["El coeficiente de difusión del carbono en la ferrita es mayor que en la austenita.",1];
Frases[27] = ["Cuanto mayor sea el porcentaje de trabajo en frío acumulado por una aleación mayor será su temperatura de recristalización.",0];
Frases[28] = ["La tensión de límite proporcional coincide con la tensión de límite elástico en aquellos materiales que sólo muestran comportamiento elástico antes de la rotura; los materiales cerámicos son un ejemplo.",1];
Frases[29] = ["En un proceso de difusión por vacantes, la difusión en volumen de grano es más rápida que la difusión en borde de grano.",0];
Frases[30] = ["En el diagrama de fases termodinámico Fe-Fe_3C, la proporción de ferrita y cementita en la perlita siempre es la misma independientemente de la composición nominal de la aleación.",1];
Frases[31] = ["Un termoplástico amorfo que opera en condiciones de servicio por debajo de su temperatura de transición vítrea está constituido por dos fases.",0];
Frases[32] = ["Cuanto mayor sea la diferencia de electronegatividad entre dos átomos mayor será la tendencia a formar un sólido iónico.",1];
Frases[33] = ["Los polímeros termoestables pueden utilizarse, por debajo de su temperatura de transición vítrea, como material estructural o resistente, es decir, con capacidad de soportar carga mecánica sin mostrar deformación plástica.",1];
Frases[34] = ["La fusión de una disolución sólida terminal, por ejemplo en un diagrama eutéctico, es congruente sólo cuando su composición química coincide con la de su elemento puro.",1];
Frases[35] = ["Las ecuaciones que permiten calcular la tensión y la deformación verdaderas sólo son válidas para valores de tensión mayores o iguales que la tensión de límite elástico y menores o iguales que la tensión máxima.",1];
Frases[36] = ["Las aleaciones hipo- y hiper-eutécticas siempre están formadas por dos microconstituyentes: 1) el primario o proeutéctico, que es distinto en ambos casos; y 2) el eutéctico o mezcla invariante que siempre es el mismo.",1];
Frases[37] = ["En un ensayo de tracción, la estricción (formación del cuello o inestabilidad plástica) es un fenómeno que tiene lugar en todos los materiales.",0];
Frases[38] = ["Al aumentar la resiliencia de un metal por deformación en frío también aumenta su dureza.",1];
Frases[39] = ["El módulo o coeficiente de Poisson se obtiene midiendo, en un ensayo normalizado de tracción, la reducción de sección respecto al alargamiento que experimenta una probeta una vez se ha roto.",0];
Frases[40] = ["Un polímero termoplástico que opera en régimen de sólido flexible puede mostrar comportamiento elástico y plástico dependiendo del valor de la tensión aplicada.",1];
Frases[41] = ["Al modificar la microestructura de un metal puro (por ejemplo, tamaño de grano y/o densidad de dislocaciones) también cambia su módulo de Young y su límite elástico.",0];
Frases[42] = ["La densidad real de un material monocristalino es siempre mayor que la teórica debido a la presencia de defectos cristalinos puntuales y lineales.",0];
Frases[43] = ["Si dos materiales poseen la misma tenacidad también tendrán la misma ductilidad.",0];
Frases[44] = ["La adición de elementos aleantes modifica, en los aceros, la composición del eutectoide. Por eso, la fase primaria que nuclea en borde de grano puede cambiar de ferrita (sin aleantes) a cementita (con aleantes).",1];
Frases[45] = ["En un diagrama de fases, un elemento puro terminal siempre presentará por debajo de su temperatura de fusión una estructura típica de material monocristalino y monofásico.",0];
Frases[46] = ["En un acero, la cantidad máxima de cementita primaria se obtiene para una composición nominal de 2.14 %wt-C.",1];
Frases[47] = ["En un diagrama de fases, un compuesto intermedio nunca puede fundir de forma congruente.",0];
Frases[48] = ["Un acero hipoeutectoide posee menor límite elástico, menor dureza y mayor tenacidad que un hipereutectoide.",1];
Frases[49] = ["Un acero hipereutectoide no puede contener nunca un 50 %-en peso de perlita.",1];
Frases[50] = ["Una curva de enfriamiento sólo muestra tramos horizontales cuando se alcanza una temperatura invariante.",1];
Frases[51] = ["En un ensayo de tracción, la ecuación de conservación de volumen es válida tanto en la zona de deformación elástica como en la zona de deformación plástica homogénea (antes de la estricción o formación del cuello).",0];
Frases[52] = ["En un ensayo de tracción uniaxial, la “tensión verdadera” (!!) y la “tensión ingenieril” (!!) se relacionan entre sí mediante la relación 𝜎_v = 𝜎_I ∙ (1 + (épsilon)) , donde (épsilon) es la “deformación ingenieril”.",1];
Frases[53] = ["La “tensión de límite elástico” (𝜎_y) de una aleación metálica estrictamente no es una propiedad del material ya que depende de la cantidad de defectos cristalinos que acumule, por ejemplo, defectos lineales y superficiales.",1];
Frases[54] = ["El mecanismo de endurecimiento por disolución sólida de tipo sustitucional produce una disminución del número de vacantes (defectos puntuales) en el material.",0];
Frases[55] = ["Al endurecer por precipitación una aleación de Aluminio se observa que su “tensión de límite elástico” (𝜎_y) aumenta con el tiempo de tratamiento térmico hasta alcanzar un valor máximo para cierto tiempo. Superado este tiempo, su 𝜎_y disminuye.",1];
Frases[56] = ["La energía interna que acumula una aleación endurecida por deformación disminuye al aplicar un tratamiento térmico de recocido en todas las etapas del proceso (restauración, recristalización y crecimiento de grano).",1];
Frases[57] = ["En el diagrama de fases Fe-Fe_3C, la austenita es una fase que se endurece al disolver en estado sólido átomos de Carbono (C) en los huecos o intersticios octaédricos de la red cristalina FCC del Hierro (Fe).",1];
Frases[58] = ["En el diagrama de fases Fe-Fe_3C, no existe ningún acero hipereutectoide que tenga el mismo porcentaje en peso de cementita y de perlita.",1];
Frases[59] = ["En el diagrama de fases Fe-Fe_3C, las fundiciones hipoeutécticas no contienen a temperatura ambiente microconstituyente eutectoide.",0];
Frases[60] = ["En el diagrama de fases Fe-Fe_3C, el acero que posee mayor porcentaje en peso de cementita primaria tiene como composición nominal el mismo porcentaje en peso de carbono que la austenita puede disolver a la temperatura invariante eutéctica.",1];
Frases[61] = ["En el diagrama de fases Fe-Fe_3C, las dos transformaciones alotrópicas del Fe se producen a las temperaturas invariantes.",0];
Frases[62] = ["En el diagrama de fases Fe-Fe_3C, a la temperatura invariante eutéctica, el número de vacantes en la austenita es mayor en los aceros hipoeutectoides que en los aceros hipereutectoides.",0];
Frases[63] = ["Al aumentar la temperatura de un acero de composición eutectoide, desde la temperatura eutectoide hasta la temperatura eutéctica, se observaría que tanto el coeficiente de difusión como la solubilidad máxima de carbono en la austenita aumentan con la temperatura.",1];
Frases[64] = ["En un diagrama de fases cuando las líneas Liquidus y Solidus coinciden siempre definen una temperatura de fusión de tipo congruente.",0];
Frases[65] = ["En cualquier diagrama de fases termodinámico (velocidad de enfriamiento muy lenta), las líneas que limitan las diferentes zonas de coexistencia entre fases se verían desplazadas si la velocidad de enfriamiento del sistema aumentara.",1];
Frases[66] = ["Si una aleación metálica se endurece por precipitación, los precipitados actúan como un mecanismo de anclaje al movimiento de las dislocaciones. Por este motivo, estos materiales son más resistentes y más frágiles.",1];
Frases[67] = ["Al solidificar una aleación líquida que sufre segregación química, debido a un enfriamiento fuera del equilibrio, se observará que su solidificación total se produce a una temperatura menor que la del diagrama de equilibrio.",1];
Frases[68] = ["Si dos elementos puros A y B cumplen 3 de las 4 reglas de Hume Rothery pueden presentar solubilidad parcial.",1];
Frases[69] = ["Si dos dislocaciones tienen signo contrario (positivo y negativo) y se mueven sobre el mismo plano de deslizamiento se repelen, es decir, una frena a la otra en su movimiento relativo hasta aniquilarse.",0];
Frases[70] = ["La energía de activación asociada al movimiento difusivo de átomos intersticiales es mayor que la asociada al movimiento de vacantes.",0];
Frases[71] = ["Cuando un elemento puro acumula en su interior átomos intersticiales debido a un proceso difusivo es necesario aplicar la segunda ley de Fick ya que se trata de un proceso no estacionario, es decir, dependiente del tiempo.",1];
Frases[72] = ["En un proceso de carburación en horno, si el material a carburar es muy grande y si la atmósfera carburante en superficie es constante, se puede utilizar como solución a la 2ª ley de Fick la solución de sólido semi-infinito.",1];
Frases[73] = ["La temperatura de fusión del Plomo (Pb) es de 327 ºC. Por tanto, a temperatura ambiente (20 ºC), el Pb no es susceptible del mecanismo de endurecimiento por deformación (es decir, no endurece por deformación).",1];
Frases[74] = ["Un polímero termoplástico puede presentar fase amorfa y fase cristalina a temperaturas inferiores a la de transición vítrea (Tg).",1];
Frases[75] = ["El porcentaje de cristalinidad que puede desarrollar un polímero termoplástico depende de su velocidad de enfriamiento. A mayor velocidad mayor porcentaje de cristalinidad.",0];
Frases[76] = ["En un polímero termoplástico semicristalino las esferulitas están formadas por cristalitas, las cuales sólo contienen fase cristalina.",0];
Frases[77] = ["La “masa molecular media en peso” (Mw) de una distribución de cadenas poliméricas da idea del peso medio de las cadenas más cortas.",0];
Frases[78] = ["Al aumentar la “masa molecular media en peso” (Mw) de un polímero termoplástico aumenta su temperatura de transición vítrea y su temperatura de fusión.",1];
Frases[79] = ["El plano {111} de la estructura FCC y el plano {0001} de la estructura HC tienen exactamente el mismo arreglo o disposición de átomos. Por tanto, la densidad planar de dichos planos es la misma.",1];
Frases[80] = ["Si una dislocación se aproxima a un borde de grano le costará menos atravesarlo en la medida en que el ángulo de desajuste de dicho borde de grano tienda o disminuya hasta cero.",1];
Frases[81] = ["Las energías de activación (E) de los procesos difusivos en volumen (V), en borde de grano (BG) y en superficie (S) se ordenan según: E_V > E_(BG) > E_S.",1];
Frases[82] = ["Si un material ensayado a tracción experimenta un porcentaje de reducción de área del 100% su ductilidad será muy pequeña.",0];
Frases[83] = ["La tenacidad es el área debajo de la curva tensión-deformación hasta rotura, es decir, la energía por unidad de volumen que un material acumula antes de romperse.",1];
Frases[84] = ["Un monocristal que endurece por deformación plástica disminuye su densidad de dislocaciones.",0];
Frases[85] = ["El mecanismo central para explicar la variación de las propiedades mecánicas de las aleaciones isomórficas binarias (o de solubilidad total) es el de endurecimiento por disolución sólida de tipo sustitucional.",1];
Frases[86] = ["Al comparar dos aleaciones isomórficas binarias (o de solubilidad total) con la misma composición química se observa que la primera funde a una mayor temperatura. Sobre la base de este resultado, se concluye que la primera fue enfriada más rápidamente que la segunda.",0];
Frases[87] = ["En un diagrama de fases eutéctico, en donde los elementos terminales son mutuamente insolubles, las fases terminales no pueden endurecerse mediante un tratamiento térmico de precipitación pero sí podrían hacerlo mediante un mecanismo de endurecimiento por deformación plástica.",1];
Frases[88] = ["En un diagrama de fases eutéctico de solubilidad parcial sí es posible obtener aleaciones segregadas químicamente.",1];
Frases[89] = ["En los diagramas de fases, si se tiene una aleación totalmente líquida que solidifica de forma incongruente, siempre se obtendrá una única fase sólida durante el proceso de solidificación.",0];
Frases[90] = ["Para aumentar significativamente el contenido de carbono de un acero hipoeutectoide mediante un proceso de disolución intersticial es necesario calentar hasta obtener una microestructura 100% de austenita.",1];
Frases[91] = ["En el diagrama de fases Fe-Fe_3C, un acero de composición química igual al valor máximo de solubilidad de C en austenita mostrará a la temperatura eutectoide la menor cantidad posible de cementita primaria.",0];
Frases[92] = ["En el diagrama de fases Fe-Fe_3C, las fundiciones hipoeutécticas muestran microconstituyente eutéctico desde la temperatura eutéctica (justo por debajo) hasta la temperatura eutectoide (justo por arriba).",1];
Frases[93] = ["El mecanismo esencial que explica la formación de perlita implica la difusión de carbono delante de las láminas de ferrita en la dirección de las láminas de cementita.",1];
Frases[94] = ["La adición de elementos aleantes puede convertir a un acero hipo-eutectoide en otro hiper-eutectoide manteniendo constante la cantidad de carbono.",1];
Frases[95] = ["La cementita es un compuesto intermetálico que sufre fusión de tipo incongruente.",0];
Frases[96] = ["Los procesos difusivos son procesos activados térmicamente que cumplen una ley de tipo Arrhenius.",1];
Frases[97] = ["Las energías de activación (E) de los procesos difusivos en volumen (V), en borde de grano (BG) y en superficie (S) se ordenan según: E_V < E_(BG) < E_S.",0];
Frases[98] = ["La energía elástica que acumula un material por deformación hasta rotura coincide con su valor de resiliencia.",1];
Frases[99] = ["La energía total que acumula un material por deformación hasta rotura coincide con su valor de tenacidad.",1];
Frases[100] = ["En la ecuación de Hall-Petch (HP) la constante de ajuste 𝜎_0 podría interpretarse como el valor de la tensión de límite elástico que tendría dicho material en el caso policristalino.",0];
Frases[101] = ["El mecanismo de endurecimiento por disolución sólida de tipo intersticial permite explicar la variación de las propiedades mecánicas de las aleaciones isomórficas binarias.",0];
Frases[102] = ["En un diagrama isomórfico binario la solubilidad de A en B o de B en A es, en ambos casos, del 50%.",0];
Frases[103] = ["En un diagrama isomórfico binario las aleaciones segregadas químicamente funden a una temperatura más alta.",0];
Frases[104] = ["En un diagrama de fases eutéctico de insolubilidad total no es posible aumentar la dureza de ninguna de las fases terminales mediante un tratamiento térmico de precipitación.",1];
Frases[105] = ["En un diagrama de fases eutéctico de solubilidad parcial sí es posible obtener aleaciones segregadas químicamente.",1];
Frases[106] = ["En un tratamiento térmico de recocido, la densidad de dislocaciones de una aleación endurecida por deformación en frío disminuye a lo largo de todas las etapas de restauración, recristalización y crecimiento de grano.",1];
Frases[107] = ["La temperatura de recristalización de una aleación endurecida por trabajo en frío es mayor cuanto mayor sea el porcentaje de trabajo en frío que acumula.",0];
Frases[108] = ["En un proceso de deformación plástica con varios pasos las propiedades mecánicas vienen fijadas en el último paso de deformación, que debe hacerse siempre en frío tras un tratamiento térmico previo de recocido.",1];
Frases[109] = ["La temperatura mínima posible a la cual habría que calentar un acero hipoeutectoide para poderlo someter a un proceso de endurecimiento por disolución sólida de tipo intersticial de carbono sería la temperatura eutectoide.",0];
Frases[110] = ["Para poder cambiar por difusión la composición química inicial de cualquier acero (hipo- y hiper-eutectoide) hasta conseguir la máxima solubilidad de carbono en austenita habría que calentar hasta la temperatura eutéctica.",1];
Frases[111] = ["En el diagrama termodinámico Fe-Fe_3C, un acero de composición química igual al valor máximo de solubilidad de C en austenita mostrará a la temperatura eutectoide la mayor cantidad posible de cementita primaria.",1];
Frases[112] = ["En el diagrama termodinámico Fe-Fe_3C, las fundiciones hipoeutécticas forman justo por debajo de la línea de solidus una mezcla formada por ledeburita primaria y austenita.",0];
Frases[113] = ["En los aceros, un incremento en la velocidad de enfriamiento permite disminuir el contenido de fase primaria.",1];
Frases[114] = ["La adición de aleantes puede convertir a un acero inicialmente hipo- en hiper-eutectoide, en cuyo caso, la fase primaria que se formaría en borde de grano de austenita, en condiciones termodinámicas, sería cementita.",1];
Frases[115] = ["La cementita es un compuesto intermetálico que sufre fusión de tipo incongruente.",0];
Frases[116] = ["Los polímeros termoplásticos sólo pueden cristalizar si sus cadenas poliméricas superan un cierto valor mínimo de longitud o, de forma equivalente, de peso molecular.",1];
Frases[117] = ["En un polímero termoplástico semicristalino los procesos difusivos de especies gaseosas son más rápidos en las zonas cristalinas que en las zonas amorfas.",0];
Frases[118] = ["La permeabilidad de un termoplástico semicristalino a distintas especies gaseosas aumenta al aumentar su porcentaje de cristalinidad.",0];
Frases[119] = ["En polímeros, la adición de grupos polares en la cadena principal hace aumentar las temperaturas de transición vítrea y de fusión.",1];
Frases[120] = ["Para que un termoplástico amorfo se comporte como un sólido flexible es necesario estar a una temperatura mayor que su temperatura de transición vítrea.",0];
Frases[121] = ["La temperatura de transición vítrea de un polímero termoplástico disminuiría con la adición de dobles enlaces o grupos laterales voluminosos en la cadena principal.",0];
Frases[122] = ["Las estructuras cristalinas FCC y HCP se generan por apilamiento de planos compactos. En dichos planos se definen las posiciones A, B y C que permiten obtener las estructuras FCC y HCP al apilar planos compactos sobre dichas posiciones.",1];
Frases[123] = ["Las estructuras cristalinas se especifican en términos de celdas unitarias paralelepipédicas, que se caracterizan por la geometría y las posiciones atómicas.",1];
Frases[124] = ["Una solución sólida se forma cuando, al adicionar átomos de soluto al solvente, la estructura cristalina se mantiene y no se forman nuevas fases.",1];
Frases[125] = ["Una dislocación es un defecto que da lugar a una distorsión de la red cristalina centrada en torno a una línea. Las dislocaciones se crean durante la solidificación de los sólidos cristalinos, pero no por deformación plástica del material.",0];
Frases[126] = ["En los procesos difusivos por vacantes, los átomos se desplazan de unas posiciones atómicas a otras siempre y cuando tengan suficiente energía para superar la energía de activación del proceso y haya vacantes donde los átomos puedan desplazarse.",1];
Frases[127] = ["El valor del coeficiente de difusión es indicativo de la velocidad de difusión atómica y depende de variables como la temperatura, el mecanismo de difusión y la estructura cristalina del solvente, pero no del tipo y el número de defectos cristalinos.",0];
Frases[128] = ["En los procesos difusivos en estado estacionario las condiciones de difusión son dependientes del tiempo.",0];
Frases[129] = ["En los diagramas isomórficos binarios, los dos elementos son completamente solubles entre sí tanto en estado sólido como líquido. En estos sistemas solo existe, en estado sólido, un tipo de estructura cristalina para todas las composiciones.",1];
Frases[130] = ["Una reacción eutéctica es una transformación de fases en la cual toda la fase líquida se transforma por enfriamiento en dos fases sólidas isotérmicamente.",1];
Frases[131] = ["En un diagrama de fases, la fusión de un compuesto intermetálico (o intermedio) es un proceso de tipo incongruente.",0];
Frases[132] = ["Los elastómeros son polímeros que poseen una estructura de cadena parcialmente entrecruzada, lo que permite que el polímero tenga una deformación elástica excepcional.",1];
Frases[133] = ["Si el peso molecular numérico medio (Mn) y el peso molecular másico medio (Mw) tienen el mismo valor, quiere decir que todas las cadenas tienen la misma longitud.",1];
Frases[134] = ["Las regiones cristalinas de los polímeros semicristalinos se denominan esferulitas, regiones donde las cadenas están plegadas y alineadas.",0];
Frases[135] = ["Para conformar un polímero termoplástico amorfo hay que superar la temperatura de fusión, mientras que para un polímero termoplástico semicristalino es suficiente con superar la Tg.",0];
Frases[136] = ["Cuando en el ensayo de tracción se observa una gran estricción del material, es indicativo de una gran ductilidad.",1];
Frases[137] = ["El módulo de Young de un material metálico es independiente de la cantidad de deformación plástica aplicada, pero sí depende de la temperatura: a mayor temperatura, menor es el módulo elástico.",1];
Frases[138] = ["La deformación transversal que experimenta un material se puede calcular a partir de la deformación longitudinal y del coeficiente de Poisson para cualquier valor de tensión aplicada.",0];
Frases[139] = ["En la curva tensión-deformación convencional (ingenieril) se observa una disminución de la tensión a partir de la tensión máxima. La disminución de la tensión con la deformación está asociada a que el material deja de endurecer por deformación plástica y cada vez es menos resistente mecánicamente.",0];
Frases[140] = ["La temperatura de recristalización de una aleación endurecida por trabajo en frío es menor cuanto mayor sea el porcentaje de trabajo en frío que acumula.",1];
Frases[141] = ["La presencia de un átomo intersticial en los alrededores de una dislocación provoca una disminución de la tensión cortante crítica del plano de deslizamiento.",0];
Frases[142] = ["En un tratamiento térmico de recocido, la densidad de dislocaciones de una aleación endurecida por deformación en frío disminuye únicamente en la etapa de recristalización.",0];
Frases[143] = ["Al apilar planos compactos siguiendo el orden de apilamiento ABCABCBACBA podemos asegurar que se ha formado un defecto de superficie llamado macla.",1];
Frases[144] = ["Los elastómeros se caracterizan por ser polímeros densamente reticulados.",0];
Frases[145] = ["Los termoestables desarrollan cristalinidad al ser inyectados en un molde si se dejan enfriar muy lentamente desde la temperatura de inyección.",0];
Frases[146] = ["El alargamiento y la estricción (o contracción lateral) permiten calcular la ductilidad y la tenacidad de un material, respectivamente.",0];
Frases[147] = ["El módulo de Young de un material metálico depende de la cantidad de deformación plástica aplicada: a mayor deformación plástica, mayor es el módulo elástico.",0];
Frases[148] = ["El límite elástico de un material metálico calculado a partir de un ensayo de tracción depende de la temperatura, de la velocidad de aplicación de la fuerza y de la sección transversal de la probeta ensayada.",0];
Frases[149] = ["La presencia de un átomo intersticial en los alrededores de una dislocación provoca un aumento de la tensión cortante crítica del plano de deslizamiento.",1];
Frases[150] = ["El coeficiente de Poisson es la relación entre la tensión y el alargamiento en campo elástico.",0];
Frases[151] = ["Los materiales cerámicos pueden endurecer por deformación plástica debido a que se aumenta la densidad de dislocaciones durante la deformación.",0];
Frases[152] = ["La temperatura de recristalización de una aleación endurecida por trabajo en frío es mayor cuanto mayor sea el porcentaje de trabajo en frío que acumula.",0];
Frases[153] = ["Al endurecer por precipitación una aleación de aluminio se observa que su límite elástico (σ_y) aumenta con el tiempo de tratamiento térmico hasta alcanzar un valor máximo para cierto tiempo. Superado este tiempo, su σ_y disminuye.",1];
Frases[154] = ["Al iniciarse la fluencia, la tensión ingenieril necesaria para continuar la deformación plástica de metales suele aumentar hasta alcanzar un valor máximo. Se puede asumir que el volumen de la probeta se mantendrá constante durante este proceso de deformación plástica hasta alcanzar el máximo.",1];
Frases[155] = ["Un material es deformado plásticamente hasta alcanzar una tensión ingenieril máxima. A partir de este punto máximo, la tensión ingenieril disminuye con la deformación debido a que la resistencia mecánica del material disminuye.",0];
Frases[156] = ["Durante un ensayo de tracción, cuando se libera la carga, se recupera una fracción de la deformación total en forma de deformación elástica.",1];
Frases[157] = ["Durante la deformación plástica, el límite de grano actúa como barrera al movimiento de dislocaciones, siendo más difícil el movimiento cuando la diferencia en la orientación cristalográfica entre dos granos contiguos es menor.",0];
Frases[158] = ["En un tratamiento térmico de recocido, la densidad de dislocaciones de una aleación endurecida por deformación en frío disminuye tanto en la etapa de restauración como de recristalización.",1];
Frases[159] = ["En un diagrama isomórfico binario o de solubilidad total, todas las composiciones químicas nominales (C0) que cumplen “0 < C0(%-en peso B) < 100” sufren fusión incongruente.",1];
Frases[160] = ["En el diagrama termodinámico Fe-Fe3C, un acero con un 2% (en peso) de carbono mostrará, a la temperatura eutectoide, mayor proporción de cementita proeutectoide que un acero de composición 1% (en peso) de carbono.",1];
Frases[161] = ["Dos muestras de polietileno (A y B) de estructura lineal tienen masas moleculares de 150.000 g/mol y 75.000 g/mol, respectivamente. Si la velocidad de enfriamiento es la misma, se puede afirmar que la muestra A presentará una menor temperatura de fusión que la muestra B.",0];
Frases[162] = ["Si tenemos un polímero termoplástico semicristalino constituido por zonas con distinto peso molecular, tendremos entonces que cada región fundirá a temperatura diferente.",1];
Frases[163] = ["En las estructuras cristalinas de los sólidos iónicos el número de coordinación de dichas estructuras aumenta al aumentar el cociente entre el radio del catión y el radio del anión.",1];
/*REAVAS*/
Frases[164] = ["Cuanto mayor sea la energía de enlace de los átomos en un material mayor será su temperatura de fusión.",1];
Frases[165] = ["El carácter iónico de un enlace entre dos átomos aumenta al aumentar la diferencia de sus electronegatividades.",1];
Frases[166] = ["Un material policristalino formado por monocristales anisotrópicos también será anisotrópico.",0];
Frases[167] = ["En una solución sólida de tipo sustitucional el número máximo de vacantes que se pueden generar depende del porcentaje en peso de átomos disueltos.",0];
Frases[168] = ["En una dislocación de cuña (o borde) su vector de Burgers indica la dirección y el sentido del deslizamiento.",1];
Frases[169] = ["Al aumentar el tamaño medio de grano en un metal disminuye su módulo de elasticidad o módulo de Young.",0];
Frases[170] = ["Los átomos de hierro no pueden difundir en la ferrita ni en la austenita; sólo los átomos de carbono pueden hacerlo.",0];
Frases[171] = ["La energía de activación asociada a un proceso de difusión por vacantes es menor que la asociada a un proceso de difusión intersticial.",0];
Frases[172] = ["En las aleaciones metálicas el módulo de elasticidad o módulo de Young disminuye al aumentar la temperatura.",1];
Frases[173] = ["La resistencia máxima a la tracción que se define en la curva “tensión verdaderadeformación verdadera” indica el inicio de la inestabilidad plástica en un material dúctil.",0];
Frases[174] = ["Si se asume que el módulo de Young permanece constante, entonces, la resiliencia de una aleación metálica aumenta al disminuir la temperatura.",1];
Frases[175] = ["Un sistema de deslizamiento está formado por el plano de mayor densidad planar y la dirección de mayor densidad lineal contenida en ese mismo plano.",1];
Frases[176] = ["En un monocristal la tensión de cizalla crítica resuelta es el doble de la tensión de límite elástico.",0];
Frases[177] = ["Si un monocristal presenta un único sistema de deslizamiento y la tensión de tracción que se aplica para deformarlo es perpendicular al plano de deslizamiento entonces cabe esperar que dicho monocristal no se deforme plásticamente y rompa frágilmente.",1];
Frases[178] = ["Las tensiones que producen deformación plástica en un aluminio policristalino son mayores que las que se necesitarían en un aluminio monocristalino.",1];
Frases[179] = ["Una solución sólida mostrará endurecimiento si los átomos de soluto son más grandes que los del disolvente pero no en el caso contrario.",0];
Frases[180] = ["Para recuperar, en un tiempo de 1 hora, las propiedades mecánicas iniciales de una aleación que ha sido endurecida por deformación hay que calentar dicha aleación a su temperatura de recristalización.",1];
Frases[181] = ["Al deformar plásticamente una aleación policristalina, los nuevos granos deformados mantienen constante su volumen.",1];
Frases[182] = ["Una aleación policristalina endurecida por deformación plástica alcanza a su temperatura de recristalización (en un tiempo de 1 hora) una estructura homogénea de nuevos granos equiaxiales de menor tamaño que los de la aleación inicial.",1];
Frases[183] = ["Las reacciones alotrópicas presentes en el diagrama de fases Fe-Fe3C (hierro-cementita) son reacciones invariantes y incongruentes.",0];
Frases[184] = ["Si se deforma una barra cilíndrica de plomo (Pb; T_(fusión)(Pb)=327 ºC) a temperatura ambiente (T_(ambiente)=20 ºC), la barra deformada mostrará una tensión de límite elástico mayor.",0];
Frases[185] = ["Al calentar un material policristalino, a una temperatura adecuada, su tamaño de grano medio y su ductilidad aumentan.",1];
Frases[186] = ["Al calentar una aleación isomórfica binaria (diagrama de fases de solubilidad total) que ha sufrido segregación química se observa que siempre funde a una temperatura menor que la que marca su diagrama de fases.",1];
Frases[187] = ["En un diagrama isomórfico binario o de solubilidad total no hay reacciones congruentes.",0];
Frases[188] = ["En un diagrama de fases eutéctico simple (1 reacción invariante), la aleación de composición eutéctica solidifica a la temperatura más baja posible, donde además, las líneas de solidus y de liquidus coinciden.",1];
Frases[189] = ["Una aleación eutectoide empieza a fundir a temperaturas ligeramente superiores a su temperatura invariante.",0];
Frases[190] = ["En un diagrama eutéctico simple (1 reacción invariante) la solubilidad máxima de las fases terminales se alcanza siempre a la temperatura invariante y es siempre distinta de cero.",0];
Frases[191] = ["Si una mezcla invariante está formada por dos soluciones sólidas, dichas soluciones sólidas poseen a la temperatura invariante valores máximos de solubilidad que no tienen por qué ser iguales.",1];
Frases[192] = ["Las aleaciones que endurecen por precipitación a cierta temperatura necesariamente son soluciones sólidas sobresaturadas de soluto a dichas temperaturas.",1];
Frases[193] = ["Una mezcla invariante eutéctica nunca tiene fase primaria o proeutéctica.",1];
Frases[194] = ["Las composiciones químicas y los porcentajes en peso de las fases presentes en una mezcla invariante no dependen de la composición nominal de la aleación.",1];
Frases[195] = ["El diagrama de fases Fe-Fe3C (hierro-cementita) siempre predice la presencia de perlita a temperatura ambiente si la composición química nominal de la aleación es mayor de un 0.02%-en peso de carbono.",1];
Frases[196] = ["En una reacción peritéctica siempre queda fase líquida después de la reacción invariante.",0];
Frases[197] = ["La reacción invariante eutéctica es congruente.",0];
Frases[198] = ["Sólo las fases terminales pueden sufrir reacciones invariantes congruentes.",0];
Frases[199] = ["Al aumentar el grado de polimerización del polietileno aumentan sus temperaturas de transición vítrea y de fusión.",1];
Frases[200] = ["La temperatura de transición vítrea de un polímero termoplástico disminuye al aumentar el número de dobles enlaces en la cadena principal.",0];
Frases[201] = ["Un polímero termoplástico en estado de sólido flexible no puede cambiar a estado de sólido vítreo por mucho que aumente la longitud media de sus cadenas poliméricas.",0];
Frases[202] = ["Un polímero termoplástico amorfo en estado de sólido vítreo se comportaría como un sólido flexible por encima de su temperatura de transición vítrea.",0];
Frases[203] = ["Los factores principales que determinan la densidad de un polímero termoestable son su peso molecular y su estructura cristalina.",0];
Frases[204] = ["En la estructura cristalina FCC, el vector de Burgers es perpendicular al vector de dirección [111].",1];
Frases[205] = ["En la estructura cristalina BCC, el vector de Burgers es paralelo al vector de dirección [111].",1];
Frases[206] = ["El plano (110) de una estructura BCC y el plano (010) de una estructura FCC, ambas con el mismo parámetro de red o arista, tienen la misma densidad planar.",0];
Frases[207] = ["En la estructura cristalina HC, al aplicar tensión en la dirección [0001], la tensión de cizalladura resuelta sobre los planos y direcciones de máxima compacidad es necesariamente igual a cero.",1];
Frases[208] = ["El oro cristaliza en la estructura FCC y el cobalto en la HC. Por tanto, ambos materiales tienen el mismo factor de empaquetamiento atómico y la misma densidad.",0];
Frases[209] = ["El titanio tiene, dependiendo de la temperatura, estructura cristalina BCC y HC. Por tanto, el titanio sufre necesariamente una reacción alotrópica a una determinada temperatura.",1];
Frases[210] = ["Si un elemento puro sufre una reacción alotrópica, el número máximo de vacantes por unidad de volumen que tendrían las dos estructuras cristalinas en equilibrio sería el mismo.",0];
Frases[211] = ["Al aumentar térmicamente el número de vacantes en un metal puro la movilidad de las dislocaciones se ve favorecida y, por tanto, la resiliencia y la tenacidad de dicho metal aumentan.",0];
Frases[212] = ["Un circuito de Burgers cerrado puede contener vacantes en su interior.",1];
Frases[213] = ["La barrera de energía que controla los procesos difusivos es menor en las disoluciones sólidas de tipo sustitucional que en las de tipo intersticial.",0];
Frases[214] = ["Si un elemento puro sufre una transformación alotrópica de BCC a FCC, la energía necesaria para generar 1 vacante en la estructura BCC será menor que en la FCC.",1];
Frases[215] = ["En un proceso difusivo no estacionario la “derivada parcial del flujo respecto del espacio” es igual a la “derivada parcial de la concentración respecto del tiempo”.",1];
Frases[216] = ["La energía necesaria para generar vacantes y la energía que controla el proceso de autodifusión (difusión de un átomo principal de la red cristalina) dependen de la temperatura de fusión del material; a mayor temperatura de fusión mayor es dicha energía.",1];
Frases[217] = ["En un ensayo de tracción el “porcentaje de reducción de área” va de “0” a “1”, siendo “0” el límite inferior para un material totalmente dúctil y “1” el límite superior para un material totalmente frágil.",0];
Frases[218] = ["En un ensayo de tracción de un material policristalino, el coeficiente de Poisson y el “porcentaje de reducción de área en zona elástica” son iguales.",0];
Frases[219] = ["La curva “tensión-deformación” ingenieril de un metal tiene un máximo. Por tanto, para tensiones verdaderas mayores que dicha tensión máxima ingenieril el metal no endurece por deformación.",0];
Frases[220] = ["Si a dos metales se les aplica el mismo porcentaje de trabajo en frío ambos tendrán la misma tensión de límite elástico.",0];
Frases[221] = ["La temperatura de recristalización es mayor para aquellos metales de mayor temperatura de fusión; sin embargo, disminuye si el porcentaje de trabajo en frío acumulado aumenta.",1];
Frases[222] = ["La temperatura de transición vítrea es mayor para aquellos termoplásticos de mayor temperatura de fusión; sin embargo, disminuye si la masa molecular media numérica aumenta.",0];
Frases[223] = ["Las disoluciones sólidas sustitucionales que cumplen todas las reglas de Hume-Rothery son susceptibles de sufrir segregación química.",1];
Frases[224] = ["Si un diagrama de fases sólo tiene dos soluciones sólidas terminales (α y β) y una reacción invariante eutéctica, las líneas Liquidus y Solidus coincidirán en las temperaturas de fusión de los elementos puros terminales (A y B) y en la de fusión del microconstituyente invariante.",1];
Frases[225] = ["En un diagrama isomórfico binario o de solubilidad total, todas las composiciones químicas nominales (C_0) que cumplen “0 < C_0(%-en peso B) < 100” sufren fusión incongruente.",1];
Frases[226] = ["Si un diagrama de fases tiene una reacción invariante eutectoide donde una de las fases que intervienen en la reacción es una fase terminal, dicha fase terminal necesariamente sufre una reacción invariante alotrópica.",1];
Frases[227] = ["Los termoplásticos tienen temperatura de fusión y temperatura de transición vítrea independientemente de la velocidad de enfriamiento.",0];
Frases[228] = ["Los termoestables desarrollan cristalinidad al ser inyectados en un molde si se dejan enfriar muy lentamente desde la temperatura de inyección.",0];
Frases[229] = ["La sustitución de 1 hidrógeno por 1 cloro en cada unidad repetitiva del polietileno incrementa la temperatura de fusión y de transición vítrea de dicho termoplástico.",1];
Frases[230] = ["La sustitución de 1 hidrógeno por 1 grupo aromático en cada unidad repetitiva del polietileno disminuye la temperatura de transición vítrea de dicho termoplástico amorfo.",0];
Frases[231] = ["La adición de grupos polares en un polietileno incrementaría su capacidad de absorción de agua.",1];
Frases[232] = ["La secuencia de empaquetamiento ABABABCABAB es hexagonal compacta (HC) pero presenta un defecto en la posición 7 que genera localmente una secuencia de empaquetamiento cúbica centrada en las caras (FCC).",1];
Frases[233] = ["La secuencia ABCABABCABC es cúbica centrada en las caras (FCC) pero presenta un defecto en la posición 6 que da lugar a una macla.",0];
Frases[234] = ["La masa molecular promedio en número (Mn) de un polímero es la masa molecular promedio de las unidades repetitivas.",0];
Frases[235] = ["Un borde de grano es un defecto lineal que se forma en la frontera de contacto entre granos contiguos.",0];
Frases[236] = ["Un defecto intersticial es un defecto puntual que se produce cuando un átomo se coloca en una posición intersticial de la red cristalina.",1];
Frases[237] = ["Las vacantes son defectos puntuales que generan distorsión localizada de la red cristalina.",1];
Frases[238] = ["El vector de Burgers de una dislocación de borde (o cuña) forma un ángulo (theta) con el vector línea de dislocación tal que (theta) = pi/2.",1];
Frases[239] = ["Los materiales amorfos presentan orden de largo alcance, pero no presentan orden de corto alcance.",0];
Frases[240] = ["La energía de activación para la difusión en volumen es menor que para la difusión superficial.",0];
Frases[241] = ["A la temperatura de transformación alotrópica, el coeficiente de autodifusión del hierro en la ferrita es mayor que en la austenita.",1];
Frases[242] = ["En un material policristalino pueden darse simultáneamente procesos de difusión atómica tanto en volumen como en borde de grano, así como en la superficie más externa del material.",1];
Frases[243] = ["El mecanismo de autodifusión es más rápido en aquellos elementos puros de mayor temperatura de fusión.",0];
Frases[244] = ["Si S1 y S2 representan dos fases sólidas y L una fase líquida, entonces la reacción química de equilibrio S1 + L ↔ S2 es de tipo peritéctico.",1];
Frases[245] = ["En una reacción de fusión congruente, la fase líquida que se forma tiene la misma composición química que la fase sólida de la que proviene.",1];
Frases[246] = ["En un diagrama de fases (termodinámico de equilibrio) de solubilidad total, la aleación de composición eutéctica funde a temperatura constante.",0];
Frases[247] = ["Una aleación de composición eutéctica (C_E) solidifica a la temperatura eutéctica (T_E) formando un sólido (o microconstituyente) de la misma composición química que el líquido, es decir, dicho sólido fundiría de forma congruente.",0];
Frases[248] = ["En un diagrama de equilibrio, las fases intermedias pueden ser un elemento puro, una solución sólida o un compuesto químico estequiométrico.",0];
Frases[249] = ["En un diagrama de fases binario (A-B) de tipo eutéctico, las aleaciones hipoeutécticas presentarán a temperatura ambiente una microestructura formada por un microconstituyente primario (o proeutéctico) rico en A y un microconstituyente eutéctico de composición eutéctica.",1];
Frases[250] = ["En un ensayo de tracción, valores elevados de estricción (o porcentaje de reducción de área) son indicativos de una alta ductilidad del material.",1];
Frases[251] = ["El módulo de elasticidad puede ser interpretado como la resistencia máxima del material antes de que se inicie la deformación plástica.",0];
Frases[252] = ["La resiliencia es una medida de la energía elástica que puede absorber un material y es directamente proporcional al módulo de Young.",0];
Frases[253] = ["La densidad de un termoplástico aumenta al aumentar su porcentaje de cristalinidad.",1];
Frases[254] = ["Al aumentar la temperatura el número de vacantes aumenta según una ley de Arrhenius. Sin embargo, la densidad del material no se ve afectada.",0];
Frases[255] = ["En un ensayo de tracción, cuando la relación entre la tensión y la deformación es lineal decimos que el material se está deformando elásticamente.",1];
Frases[256] = ["Un metal en estado de recocido que se deforma en frío tiene menor resistencia mecánica después del proceso de deformación.",0];
Frases[257] = ["En la estructura BCC, la relación entre el radio del átomo (R) y la arista de la celdilla (a) es a = 4·R/sqrt(2).",0];
Frases[258] = ["La recristalización de un metal ocurre a menores temperaturas cuando éste tiene un alto grado de deformación o trabajo en frío acumulado.",1];
Frases[259] = ["Para encontrar una solución a la segunda ley de Fick se aplican condiciones de contorno de sólido semiinfinito.",1];
Frases[260] = ["Una aleación metálica que ha sido recristalizada después de una etapa de deformación frío muestra menor dureza y mayor ductilidad.",1];
Frases[261] = ["En un tratamiento térmico de recocido, la etapa de recristalización es anterior a la etapa de recuperación.",0];
Frases[262] = ["En un proceso difusivo estacionario, el flujo de materia (J) varía exponencialmente con la energía de activación del proceso para la solución sólida estudiada, siendo J mayor cuando la compacidad de la red cristalina es menor.",1];
Frases[263] = ["La temperatura de fusión de una aleación eutéctica se encuentra entre las temperaturas de fusión de los dos metales puros que forman dicha aleación.",0];
Frases[264] = ["Para un material policristalino, la difusión es más rápida en materiales con estructura de grano fino que con estructuras de grano grande.",1];
Frases[265] = ["En los aceros hipereutectoides, la cementita aparece en los bordes de grano y en la perlita.",1];
Frases[266] = ["Un monómero es una molécula a partir de la cual se produce un polímero.",1];
Frases[267] = ["Copolímero es un polímero producido al unir más de un tipo de monómero.",1];
Frases[268] = ["Al calentar moderadamente un polímero termoplástico se rompen los enlaces Van der Waals entre cadenas, de forma que el polímero se degrada completamente y no se puede reciclar.",0];
Frases[269] = ["Polimerización por adición es el proceso mediante el cual se elaboran cadenas de polímeros mediante la adición de monómeros sin crear subproductos.",1];
Frases[270] = ["El alargamiento y la estricción son indicativas de la ductilidad de los materiales.",1];
Frases[271] = ["Los elastómeros son polímeros que poseen una estructura molecular parcialmente entrecruzada, lo que permite que el polímero tenga una gran deformación elástica.",1];
Frases[272] = ["Cuando en el ensayo de tracción la estricción (o reducción de área) de la probeta es muy grande, es indicativo de una alta ductilidad y de un módulo de Young elevado.",0];
Frases[273] = ["Un enfriamiento muy rápido de la austenita da lugar a martensita. Durante esta transformación martensítica se producen fenómenos de difusión que dan lugar a cambios en la estructura cristalina y la composición química.",0];
Frases[274] = ["Los procesos de deformación plástica, como el trabajo en frío, aumentan tanto el límite elástico como la resistencia máxima y la ductilidad de un material.",0];
Frases[275] = ["Los límites de grano, regiones que separan granos o cristales con orientación cristalográfica diferentes, se consideran defectos lineales.",0];
Frases[276] = ["Las estructuras FCC y BCC tienen diferente valor del factor de empaquetamiento atómico porque las dos estructuras están formadas por planos de diferente compacidad.",1];
Frases[277] = ["Las cadenas de un polímero termoestable están unidas entre sí por enlaces covalentes, motivo por el que estos polímeros son más duros y resistentes que los termoplásticos.",1];
Frases[278] = ["La resistencia a la tracción de un material metálico calculada a partir de un ensayo de tracción depende de la temperatura y de la velocidad de aplicación de la carga, pero no depende de la sección transversal de la probeta ensayada.",1];
Frases[279] = ["La temperatura de recristalización de una aleación endurecida por trabajo en frío disminuye al aumentar el porcentaje de trabajo en frío.",1];
Frases[280] = ["La deformación plástica en los metales ocurre por el movimiento de las dislocaciones, que se desplazan como consecuencia de estar sometidas a tensiones de tracción.",0];
Frases[281] = ["Un metal endurecerá por solución sólida cuando el radio del átomo de soluto sea mayor que el radio del átomo de disolvente, pero no cuando aquél sea menor.",0];
Frases[282] = ["En empaquetamientos compactos, el número de huecos tetraédricos es el doble del número de huecos octaédricos.",1];
Frases[283] = ["Durante un proceso de difusión en estado no estacionario tanto el flujo como el gradiente de concentración varían con el tiempo, dando lugar a una acumulación de la especie que difunde en el interior del material.",1];
Frases[284] = ["La energía elástica que acumula un material por unidad de volumen es directamente proporcional a su módulo de Young.",0];
Frases[285] = ["El incremento en las propiedades mecánicas de resistencia máxima y límite elástico de un metal deformado en frío se debe a una disminución de la densidad de dislocaciones con respecto al metal no deformado.",0];
/*POLIMEROS PARCIALES RANDOM*/
Frases[286] = ["La masa molecular media numérica es menor que la masa molecular media en peso.",1];
Frases[287] = ["La masa molecular media numérica da una idea de la masa molecular media de las cadenas poliméricas cortas, que se encuentran, por tanto, en mayor presencia numérica.",1];
Frases[288] = ["La masa molecular media en peso da una idea de la masa molecular media de las cadenas poliméricas largas, que se encuentran, por tanto, en menor presencia numérica.",1];
Frases[289] = ["La densidad de un cristal homopolímero de cadena lineal es directamente proporcional a la masa molecular de su unidad repetitiva.",1];
Frases[290] = ["Un termoplástico en estado de sólido flexible está formado por fase cristalina y fase amorfa. Por tanto, su densidad será menor que la densidad de la fase cristalina y mayor que la de la fase amorfa.",1];
Frases[291] = ["La sustitución aleatoria de átomos de hidrógeno por átomos de cloro en el polietileno aumenta la temperatura de transición vítrea y disminuye la temperatura de fusión del material resultante.",0];
Frases[292] = ["La longitud total de la cadena polimérica media es inversamente proporcional a la masa molecular media numérica de la distribución de cadenas poliméricas.",0];
Frases[293] = ["La longitud total de la cadena polimérica media es directamente proporcional al grado de polimerización.",1];
Frases[294] = ["Las cadenas poliméricas se pliegan así mismas durante el proceso de polimerización. Por tanto, la distancia entre el principio y el final de la cadena es siempre menor que su longitud total.",1];
Frases[295] = ["Si la masa molecular media numérica de un determinado polímero disminuye, también disminuirá la distancia media entre el principio y el final de sus cadenas poliméricas.",1];
Frases[296] = ["Sólo es posible obtener copolímeros alternados si la fracción en peso de las dos unidades repetitivas es igual a 1. En cualquier otro caso se formarán copolímeros al azar, en bloque o de injerto.",1];
Frases[297] = ["En un termoplástico semicristalino, la presencia de dobles enlaces en la cadena principal y la adición de grupos polares y/o grupos laterales voluminosos aumenta su temperatura de transición vítrea.",1];
Frases[298] = ["La cristalinidad de un termoestable depende de la velocidad de enfriamiento, siendo ésta menor cuanto mayor sea dicha velocidad.",0];
Frases[299] = ["Los materiales termoplásticos y los elastómeros presentan flujo viscoso por encima de su temperatura de transición vítrea.",0];
Frases[300] = ["Un polímero termoplástico presenta siempre dos fases independientemente del estado de agregación en que se encuentre.",0];
Frases[301] = ["En condiciones normales de solidificación, un material policristalino es anisotrópico si los monocristales que lo forman son anisotrópicos.",0];
/*Frases[] = ["",];*/

var Q = Frases.length;
var Aleatori = Math.round(Math.random()*(Q-1));
/*function ShowFrase(){
	document.write(Frases[Aleatori][0]);
}*/
document.getElementById("idfrases").innerHTML = Frases[Aleatori][0];

var errades = 0;
var correctes = 0;

document.getElementById("verdader").addEventListener("click", function(){resposta(1);});
document.getElementById("fals").addEventListener("click", function(){resposta(0);});
document.getElementById("seguent").addEventListener("click", function(){passa()});

function resposta(res){
	if(res == Frases[Aleatori][1]) {
		document.getElementById("solucio").innerHTML = "¡Correcto!";
		document.getElementById("fals").disabled = true;
		document.getElementById("verdader").disabled = true;
		correctes++;
		Frases[Aleatori][1] = 2 /**/
		document.getElementById("estanbe").innerHTML = "Correctas: "+correctes;
		document.getElementById("estanmalament").innerHTML = "Errores: "+errades;
	}
	else if(res != Frases[Aleatori][1]) {
		document.getElementById("solucio").innerHTML = "¡Nooo! ¡Mal!";
		document.getElementById("fals").disabled = true;
		document.getElementById("verdader").disabled = true;
		errades++;
		document.getElementById("estanbe").innerHTML = "Correctas: "+correctes;
		document.getElementById("estanmalament").innerHTML = "Errores: "+errades;
	}
}

function passa(){
	if(correctes == Q) acaba(); /**/
	else { /**/
		Aleatori = Math.round(Math.random()*(Q-1));
		if(Frases[Aleatori][1] == 2) passa2(); /**/
		else{ /**/
			document.getElementById("idfrases").innerHTML = Frases[Aleatori][0];
			document.getElementById("solucio").innerHTML = "";
			document.getElementById("verdader").disabled = false;
			document.getElementById("fals").disabled = false;
		}
	}
}

function passa2(){
	Aleatori++;
	if(Frases[Aleatori][1] == 2) passa2()
	else {
		document.getElementById("idfrases").innerHTML = Frases[Aleatori][0];
		document.getElementById("solucio").innerHTML = "";
		document.getElementById("verdader").disabled = false;
		document.getElementById("fals").disabled = false;
	}
}

function acaba(){
	document.getElementById("idfrases").innerHTML = "¡Felicidades! ¡Has acertado todas las frases que había disponibles! Cada vez estás mas preparad@ para el examen.";
	document.getElementById("seguent").innerHTML = "Acabado";
	document.getElementById("seguent").disabled = true;
}